apiVersion: v1
kind: Namespace
metadata:
 name: middleware

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: middleware
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: a8EyHxVuaZeS9J
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: base-mysql-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        dbnode: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/mysql/data
          type: ""
        name: base-mysql-data

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: middleware
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql57
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 23306
  selector:
    app: mysql
  sessionAffinity: None
  type: NodePort