// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClusterBind = "cluster_bind"

// ClusterBind mapped from table <cluster_bind>
type ClusterBind struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID   string    `gorm:"column:project_id;not null;default:0" json:"project_id"`
	ClusterID   string    `gorm:"column:cluster_id;not null;default:0" json:"cluster_id"`
	ProjectName string    `gorm:"column:project_name;not null" json:"project_name"`
	ClusterName string    `gorm:"column:cluster_name;not null" json:"cluster_name"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ClusterBind's table name
func (*ClusterBind) TableName() string {
	return TableNameClusterBind
}
