// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCluster = "cluster"

// Cluster mapped from table <cluster>
type Cluster struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClusterID   string    `gorm:"column:cluster_id;not null;default:0" json:"cluster_id"`
	ClusterName string    `gorm:"column:cluster_name;not null" json:"cluster_name"`
	Describe    string    `gorm:"column:describe;not null" json:"describe"`
	Labels      string    `gorm:"column:labels;not null" json:"labels"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Cluster's table name
func (*Cluster) TableName() string {
	return TableNameCluster
}
