// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLabel = "label"

// Label mapped from table <label>
type Label struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	LabelID   string    `gorm:"column:label_id;not null;default:0" json:"label_id"`
	Key       string    `gorm:"column:key;not null" json:"key"`
	Value     string    `gorm:"column:value;not null" json:"value"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Label's table name
func (*Label) TableName() string {
	return TableNameLabel
}
