// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID   string    `gorm:"column:project_id;not null;default:0" json:"project_id"`
	ProjectName string    `gorm:"column:project_name;not null" json:"project_name"`
	Describe    string    `gorm:"column:describe;not null" json:"describe"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
