// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceaccount = "serviceaccount"

// Serviceaccount mapped from table <serviceaccount>
type Serviceaccount struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SaID      string    `gorm:"column:sa_id;not null;default:0" json:"sa_id"`
	SaName    string    `gorm:"column:sa_name;not null" json:"sa_name"`
	SaToken   string    `gorm:"column:sa_token;not null" json:"sa_token"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Serviceaccount's table name
func (*Serviceaccount) TableName() string {
	return TableNameServiceaccount
}
