// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cluster/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreateCluster"
                ],
                "summary": "CreateCluster",
                "operationId": "CreateCluster",
                "parameters": [
                    {
                        "description": "Create Cluster",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cluster.CreateClusterRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/cluster/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DeleteCluster"
                ],
                "summary": "DeleteCluster",
                "operationId": "DeleteCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster_Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/cluster/get_id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get ClusterID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetClusterId"
                ],
                "summary": "GetClusterId",
                "operationId": "GetClusterId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/cluster/label": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List Cluster for label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListGetLabel"
                ],
                "summary": "ListGetLabel",
                "operationId": "ListGetLabel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Label Key",
                        "name": "label_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Label value",
                        "name": "label_value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/cluster/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List  Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListCluster"
                ],
                "summary": "ListCluster",
                "operationId": "ListCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cluster Name",
                        "name": "cluster_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/cluster/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UpdateCluster"
                ],
                "summary": "UpdateCluster",
                "operationId": "UpdateCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster_ID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Update Cluster",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cluster.UpdateClusterRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/label/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create Label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreateLabel"
                ],
                "summary": "CreateLabel",
                "operationId": "CreateLabel",
                "parameters": [
                    {
                        "description": "Create Label",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/label.CreateLabelRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/label/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete Label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DeleteLabel"
                ],
                "summary": "DeleteLabel",
                "operationId": "DeleteLabel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster_Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Label_Key",
                        "name": "label_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Label_value",
                        "name": "label_value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/label/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List Cluster's label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListClusterLabel"
                ],
                "summary": "ListClusterLabel",
                "operationId": "ListClusterLabel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/project/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreateProject"
                ],
                "summary": "CreateProject",
                "operationId": "CreateProject",
                "parameters": [
                    {
                        "description": "Create Project",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.CreateProjectRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/project/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DeleteProject"
                ],
                "summary": "DeleteProject",
                "operationId": "DeleteProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/project/get_id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get ProjectID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetProjectId"
                ],
                "summary": "GetProjectId",
                "operationId": "GetProjectId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/project/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListProject"
                ],
                "summary": "ListProject",
                "operationId": "ListProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/project/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UpdateProject"
                ],
                "summary": "UpdateProject",
                "operationId": "UpdateProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Update Project",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.CreateProjectRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/addns": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "ADD ServiceAccount NameSpace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AddNameSpace"
                ],
                "summary": "AddNameSpace",
                "operationId": "AddNameSpace",
                "parameters": [
                    {
                        "description": "Add Sa NameSpace",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serviceaccount.AddSaNsRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create ServiceAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreateSa"
                ],
                "summary": "CreateSa",
                "operationId": "CreateSa",
                "parameters": [
                    {
                        "description": "Create Sa",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serviceaccount.CreateSaRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete ServiceAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DeleteSa"
                ],
                "summary": "DeleteSa",
                "operationId": "DeleteSa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster_Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sa_name",
                        "name": "sa_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/delns": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete ServiceAccount NameSpace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DeleteNs"
                ],
                "summary": "DeleteNs",
                "operationId": "DeleteNs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster_Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sa_Name",
                        "name": "sa_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NameSpace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/gettoken": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get SaToken For NameSpace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gettoken"
                ],
                "summary": "Gettoken",
                "operationId": "Gettoken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ns_Name",
                        "name": "ns_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List All ServiceAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListSa"
                ],
                "summary": "ListSa",
                "operationId": "ListSa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sa Name",
                        "name": "sa_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/listns": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List All ServiceAccount's NameSpace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListNs"
                ],
                "summary": "ListNs",
                "operationId": "ListNs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sa_Name",
                        "name": "sa_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/sa/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update ServiceAccount SaToken",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UpdateSaToken"
                ],
                "summary": "UpdateSaToken",
                "operationId": "UpdateSa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project_Name",
                        "name": "project_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster_Name",
                        "name": "cluster_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sa_Name",
                        "name": "sa_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Update ServiceAccount Token",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/serviceaccount.UpdateSaRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/list": {
            "get": {
                "description": "List User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListUser"
                ],
                "summary": "ListUser",
                "operationId": "ListUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserName",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "get": {
                "description": "User Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Login",
                "operationId": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserName",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PassWord",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Register User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RegisterUser"
                ],
                "summary": "RegisterUser",
                "operationId": "RegisterUser",
                "parameters": [
                    {
                        "description": "Register User",
                        "name": "ReqeustBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        },
        "/user/verifytoken": {
            "get": {
                "description": "Verify Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VerifyToken"
                ],
                "summary": "VerifyToken",
                "operationId": "VerifyToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"data\":null,\"msg\":\"\"}",
                        "schema": {
                            "$ref": "#/definitions/util.Res"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cluster.CreateClusterRequestBody": {
            "type": "object",
            "required": [
                "cluster_name",
                "project_name"
            ],
            "properties": {
                "cluster_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                }
            }
        },
        "cluster.UpdateClusterRequestBody": {
            "type": "object",
            "properties": {
                "cluster_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "label.CreateLabelRequestBody": {
            "type": "object",
            "required": [
                "cluster_name",
                "label_key",
                "label_value",
                "project_name"
            ],
            "properties": {
                "cluster_name": {
                    "type": "string"
                },
                "label_key": {
                    "type": "string"
                },
                "label_value": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                }
            }
        },
        "project.CreateProjectRequestBody": {
            "type": "object",
            "required": [
                "description",
                "project_name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                }
            }
        },
        "serviceaccount.AddSaNsRequestBody": {
            "type": "object",
            "required": [
                "cluster_name",
                "namespace",
                "project_name",
                "sa_name"
            ],
            "properties": {
                "cluster_name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                },
                "sa_name": {
                    "type": "string"
                }
            }
        },
        "serviceaccount.CreateSaRequestBody": {
            "type": "object",
            "required": [
                "cluster_name",
                "namespace",
                "project_name",
                "sa_name",
                "sa_token"
            ],
            "properties": {
                "cluster_name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                },
                "sa_name": {
                    "type": "string"
                },
                "sa_token": {
                    "type": "string"
                }
            }
        },
        "serviceaccount.UpdateSaRequestBody": {
            "type": "object",
            "required": [
                "sa_token"
            ],
            "properties": {
                "sa_token": {
                    "type": "string"
                }
            }
        },
        "user.CreateUserRequestBody": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "util.Res": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
